import { Lato } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/themeContext";
import AppShell from "@/components/Appshell/page";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Aldi's Web",
  description: "Generated by Aldi's Web",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <ThemeProvider>
          <AppShell>{children}</AppShell>
        </ThemeProvider>
      </body>
    </html>
  );
}
